LANGUAGE_ALIASES = {
    "acehnese": "ace_Latn",
    "acholi": "ach_Latn",
    "afrikaans": "afr_Latn",
    "akan": "aka_Latn",
    "alzateco": "alz_Latn",
    "amharic": "amh_Ethi",
    "arabic": "arb_Arab",
    "modern_standard_arabic": "arb_Arab",
    "levantine_arabic": "apc_Arab",
    "gulf_arabic": "afb_Arab",
    "egyptian_arabic": "arz_Arab",
    "moroccan_arabic": "ary_Arab",
    "tunisian_arabic": "aeb_Arab",
    "algerian_arabic": "arq_Arab",

    "assamese": "asm_Beng",
    "asturian": "ast_Latn",
    "aymara": "ayr_Latn",
    "azerbaijani": "azj_Latn",

    "bambara": "bam_Latn",
    "balinese": "ban_Latn",
    "bengali": "ben_Beng",
    "bangla": "ben_Beng",
    "bhojpuri": "bho_Deva",
    "bislama": "bis_Latn",
    "bosnian": "bos_Latn",
    "buginese": "bug_Latn",
    "bulgarian": "bul_Cyrl",
    "burmese": "mya_Mymr",

    "cantonese": "yue_Hant",
    "cebuano": "ceb_Latn",
    "chinese": "zho_Hans",
    "simplified_chinese": "zho_Hans",
    "traditional_chinese": "zho_Hant",
    "chuvash": "chv_Cyrl",
    "cornish": "cor_Latn",
    "croatian": "hrv_Latn",
    "czech": "ces_Latn",

    "danish": "dan_Latn",
    "dhivehi": "div_Thaa",
    "dutch": "nld_Latn",
    "dzongkha": "dzo_Tibt",

    "english": "eng_Latn",
    "esperanto": "epo_Latn",
    "estonian": "est_Latn",
    "ewe": "ewe_Latn",

    "faroese": "fao_Latn",
    "fijian": "fij_Latn",
    "filipino": "fil_Latn",
    "finnish": "fin_Latn",
    "flemish": "vls_Latn",
    "french": "fra_Latn",

    "galician": "glg_Latn",
    "ganda": "lug_Latn",
    "georgian": "kat_Geor",
    "german": "deu_Latn",
    "greek": "ell_Grek",
    "guarani": "gnw_Latn",
    "gujarati": "guj_Gujr",

    "haitian_creole": "hat_Latn",
    "hausa": "hau_Latn",
    "hawaiian": "haw_Latn",
    "hebrew": "heb_Hebr",
    "hiligaynon": "hil_Latn",
    "hindi": "hin_Deva",
    "hindustani": "hin_Deva",
    "hmong": "hmn_Latn",
    "hungarian": "hun_Latn",

    "icelandic": "isl_Latn",
    "igbo": "ibo_Latn",
    "ilocano": "ilo_Latn",
    "indonesian": "ind_Latn",
    "irish": "gle_Latn",
    "italian": "ita_Latn",

    "japanese": "jpn_Jpan",
    "javanese": "jav_Latn",

    "kabyle": "kab_Latn",
    "kannada": "kan_Knda",
    "kazakh": "kaz_Cyrl",
    "khmer": "khm_Khmr",
    "kikuyu": "kik_Latn",
    "kinyarwanda": "kin_Latn",
    "kirundi": "run_Latn",
    "korean": "kor_Hang",
    "kurdish_kurmanji": "kmr_Latn",
    "kurdish_sorani": "ckb_Arab",
    "kyrgyz": "kir_Cyrl",

    "lao": "lao_Laoo",
    "latin": "lat_Latn",
    "latvian": "lvs_Latn",
    "lingala": "lin_Latn",
    "lithuanian": "lit_Latn",
    "luganda": "lug_Latn",
    "luxembourgish": "ltz_Latn",

    "macedonian": "mkd_Cyrl",
    "maithili": "mai_Deva",
    "malagasy": "plt_Latn",
    "malay": "zsm_Latn",
    "malayalam": "mal_Mlym",
    "maltese": "mlt_Latn",
    "maori": "mri_Latn",
    "marathi": "mar_Deva",
    "meitei": "mni_Mtei",
    "mongolian": "mon_Cyrl",

    "nepali": "npi_Deva",
    "norwegian": "nob_Latn",

    "occitan": "oci_Latn",
    "odia": "ory_Orya",
    "ojibwe": "oji_Latn",
    "oromo": "orm_Latn",

    "pashto": "pbt_Arab",
    "persian": "pes_Arab",
    "polish": "pol_Latn",
    "portuguese": "por_Latn",
    "punjabi": "pan_Guru",

    "quechua": "quy_Latn",

    "romanian": "ron_Latn",
    "rundi": "run_Latn",
    "russian": "rus_Cyrl",

    "samoan": "smo_Latn",
    "sanskrit": "san_Deva",
    "scottish_gaelic": "gla_Latn",
    "serbian": "srp_Cyrl",
    "sindhi": "snd_Arab",
    "sinhala": "sin_Sinh",
    "slovak": "slk_Latn",
    "slovenian": "slv_Latn",
    "somali": "som_Latn",
    "sotho": "sot_Latn",
    "spanish": "spa_Latn",
    "sundanese": "sun_Latn",
    "swahili": "swh_Latn",
    "swedish": "swe_Latn",

    "tajik": "tgk_Cyrl",
    "tamil": "tam_Taml",
    "tatar": "tat_Cyrl",
    "telugu": "tel_Telu",
    "thai": "tha_Thai",
    "tigrinya": "tir_Ethi",
    "tongan": "ton_Latn",
    "tsonga": "tso_Latn",
    "turkish": "tur_Latn",
    "turkmen": "tuk_Latn",

    "ukrainian": "ukr_Cyrl",
    "urdu": "urd_Arab",
    "uyghur": "uig_Arab",
    "uzbek": "uzn_Latn",

    "vietnamese": "vie_Latn",
    "visayan": "war_Latn",

    "welsh": "cym_Latn",
    "wolof": "wol_Latn",

    "xhosa": "xho_Latn",

    "yiddish": "ydd_Hebr",
    "yoruba": "yor_Latn",

    "zulu": "zul_Latn"
}
